FROM node:20-alpine

# Seta o diretório de trabalho para o frontend no monorepo
WORKDIR /app/apps/web

# Copia apenas os arquivos de dependência do frontend
COPY apps/web/package*.json ./

# Instala dependências do frontend
RUN npm install

# Copia o restante do projeto monorepo
COPY . .

CMD ["npm", "run", "dev"]
