services:
  postgres:
    image: postgres:15
    restart: always
    container_name: zion-postgres
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "${DB_PORT}:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - zion-net

  redis:
    image: redis:7
    container_name: zion-redis
    ports:
      - "${REDIS_PORT}:6379"
    networks:
      - zion-net

volumes:
  pgdata:

networks:
  zion-net:
    driver: bridge